# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import datetime
from recommonmark.parser import CommonMarkParser
sys.path.insert(0, os.path.abspath('.'))
sys.path.append(os.path.abspath('exts'))

# -- Project information -----------------------------------------------------

project = 'Appunti di Dag7'
copyright = 'CC BY-NC 4.0'
author = 'Damiano Gualandri dag7'

# The short X.Y version
version = '0.1'
# The full version, including alpha/beta/rc tags
release = '0.1-draft'
# consente di avere la numerazione delle figure
numfig = True

# -- General configuration ---------------------------------------------------

source_parsers = {
    '.md': CommonMarkParser,
}

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.githubpages',
    'sphinx.ext.autodoc',
    'sphinx.ext.imgmath',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
#source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#

# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'it'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
html_logo = ""

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

html_theme_options = {
    'logo_only': True,
    'display_version': False,
}

html_context = {
    "display_github": True,  # Integrate Gitlab
    "conf_py_path": "/docs/source/",  # Path in the checkout to the docs root

    "author": 'Dag7',
    #    "date": datetime.date.today().strftime('%d/%m/%y'),
}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'AppuntiPersonaliDag7'


# -- Options for LaTeX output ------------------------------------------------
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    'pointsize': '12pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    'figure_align': 'htbp',
}

# Copy button and Justify Text


def setup(app):
    app.add_css_file('colors.css')
    app.add_css_file('custom.css')
    app.add_js_file("custom.js")
    app.add_js_file(
        "https://cdn.jsdelivr.net/npm/clipboard@1/dist/clipboard.min.js")


rst_prolog = """
.. include:: /_static/.special.rst
"""

rst_epilog = """
.. |action_canceled| replace:: :annullato:`Canceled`
.. |action_open| replace:: :aperto:`Open`
.. |action_reopen| replace:: :aperto:`reOpen`
.. |action_hold| replace:: :hold:`Hold`
.. |action_new| replace:: :nuovo:`New`
.. |action_closed| replace:: :chiuso:`Closed`
.. |hline| raw:: html

    <hr/>
"""

html_last_updated_fmt = '%d %b %Y, %X'
